// ============================================================
// Data/Migrations/InitialCreate.cs
//
// This migration is equivalent to your setup.sql file.
// EF Core generates SQL from your C# models and runs it.
//
// HOW TO USE:
//   Run: dotnet ef migrations add InitialCreate
//   Run: dotnet ef database update
//
// OR: Program.cs already calls db.Database.Migrate() on startup,
// which auto-applies this when you first run the app.
// ============================================================

// NOTE: This is a GUIDE file showing the equivalent SQL that EF Core
// generates. The actual migration file is auto-generated by:
//   dotnet ef migrations add InitialCreate
//
// The SQL EF Core generates matches your setup.sql exactly:

/*
   CREATE TABLE `course` (
       `course_id` int NOT NULL AUTO_INCREMENT,
       `course_name` varchar(100) NOT NULL,
       PRIMARY KEY (`course_id`)
   );

   CREATE TABLE `section` (
       `section_id` int NOT NULL AUTO_INCREMENT,
       `section_name` varchar(50) NOT NULL,
       PRIMARY KEY (`section_id`)
   );

   CREATE TABLE `gender` (
       `gender_id` int NOT NULL AUTO_INCREMENT,
       `gender_name` varchar(20) NOT NULL,
       PRIMARY KEY (`gender_id`)
   );

   CREATE TABLE `subject` (
       `subject_id` int NOT NULL AUTO_INCREMENT,
       `subject_name` varchar(100) NOT NULL,
       PRIMARY KEY (`subject_id`)
   );

   CREATE TABLE `students` (
       `student_id` int NOT NULL AUTO_INCREMENT,
       `first_name` varchar(50) NOT NULL,
       `last_name` varchar(50) NOT NULL,
       `birthdate` date NOT NULL,
       `course_id` int NOT NULL,
       `section_id` int NOT NULL,
       `gender_id` int NOT NULL,
       PRIMARY KEY (`student_id`),
       FOREIGN KEY (`course_id`) REFERENCES `course` (`course_id`),
       FOREIGN KEY (`section_id`) REFERENCES `section` (`section_id`),
       FOREIGN KEY (`gender_id`) REFERENCES `gender` (`gender_id`)
   );

   CREATE TABLE `student_grades` (
       `grade_id` int NOT NULL AUTO_INCREMENT,
       `student_id` int NOT NULL,
       `subject_id` int NOT NULL,
       `grade` decimal(5,2) NOT NULL,
       PRIMARY KEY (`grade_id`),
       FOREIGN KEY (`student_id`) REFERENCES `students` (`student_id`) ON DELETE CASCADE,
       FOREIGN KEY (`subject_id`) REFERENCES `subject` (`subject_id`)
   );
*/

// The DbDataSeeder below seeds initial data (same as your INSERT INTO statements)

namespace StudentMS.Api.Data;

public static class DbDataSeeder
{
    /// <summary>
    /// Seeds the database with initial lookup data.
    /// Call this from Program.cs after migration.
    /// Equivalent to the INSERT INTO blocks in your setup.sql
    /// </summary>
    public static async Task SeedAsync(ApplicationDbContext db)
    {
        // Only seed if tables are empty
        if (!db.Courses.Any())
        {
            db.Courses.AddRange(
                new Models.Course { CourseName = "Bachelor of Science in Information Technology" },
                new Models.Course { CourseName = "Bachelor of Science in Computer Science" },
                new Models.Course { CourseName = "Bachelor of Science in Education" },
                new Models.Course { CourseName = "Bachelor of Science in Nursing" },
                new Models.Course { CourseName = "Bachelor of Science in Business Administration" }
            );
        }

        if (!db.Sections.Any())
        {
            db.Sections.AddRange(
                new Models.Section { SectionName = "Section A" },
                new Models.Section { SectionName = "Section B" },
                new Models.Section { SectionName = "Section C" },
                new Models.Section { SectionName = "Section D" }
            );
        }

        if (!db.Genders.Any())
        {
            db.Genders.AddRange(
                new Models.Gender { GenderName = "Male" },
                new Models.Gender { GenderName = "Female" },
                new Models.Gender { GenderName = "Prefer no to say" }
            );
        }

        if (!db.Subjects.Any())
        {
            db.Subjects.AddRange(
                new Models.Subject { SubjectName = "Mathematics" },
                new Models.Subject { SubjectName = "English" },
                new Models.Subject { SubjectName = "Science" },
                new Models.Subject { SubjectName = "Filipino" },
                new Models.Subject { SubjectName = "Physical Education" },
                new Models.Subject { SubjectName = "Information Technology" },
                new Models.Subject { SubjectName = "Programming Fundamentals" }
            );
        }

        await db.SaveChangesAsync();
    }
}
